### ISSUE TITLE
Failed to resolve import Vue

### ISSUE THREAD

**Issue by Kingside88** [taikio/nuxt-3-oidc-auth#1]
Thank you for this example but unfortunatly I get this error, when I try to run it:
It did nothing else than clone it, `pnpm install` and `pnpm run dev`

```
 Internal server error: Failed to resolve import "vue" from "node_modules\.pnpm\nuxt@3.3.1_eslint@8.36.0+sass@1.60.0\node_modules\nuxt\dist\app\entry.js?v=353ecaa2". Does the file exist?
  Plugin: vite:import-analysis
  File: C:/Users/andre/source/repos/nuxt-3-oidc-auth/node_modules/.pnpm/nuxt@3.3.1_eslint@8.36.0+sass@1.60.0/node_modules/nuxt/dist/app/entry.js?v=353ecaa2:1:52
  1  |  import { createSSRApp, createApp, nextTick } from "vue";
     |                                                     ^
  2  |  import { $fetch } from "ofetch";
  3  |  import { baseURL } from "#build/paths.mjs";
      at formatError (file:///C:/Users/andre/source/repos/nuxt-3-oidc-auth/node_modules/.pnpm/vite@4.1.4_sass@1.60.0/node_modules/vite/dist/node/chunks/dep-ca21228b.js:41418:46)
      at TransformContext.error (file:///C:/Users/andre/source/repos/nuxt-3-oidc-auth/node_modules/.pnpm/vite@4.1.4_sass@1.60.0/node_modules/vite/dist/node/chunks/dep-ca21228b.js:41414:19)
      at normalizeUrl (file:///C:/Users/andre/source/repos/nuxt-3-oidc-auth/node_modules/.pnpm/vite@4.1.4_sass@1.60.0/node_modules/vite/dist/node/chunks/dep-ca21228b.js:39706:33)
      at async TransformContext.transform (file:///C:/Users/andre/source/repos/nuxt-3-oidc-auth/node_modules/.pnpm/vite@4.1.4_sass@1.60.0/node_modules/vite/dist/node/chunks/dep-ca21228b.js:39840:47)
      at async Object.transform (file:///C:/Users/andre/source/repos/nuxt-3-oidc-auth/node_modules/.pnpm/vite@4.1.4_sass@1.60.0/node_modules/vite/dist/node/chunks/dep-ca21228b.js:41685:30)
      at async loadAndTransform (file:///C:/Users/andre/source/repos/nuxt-3-oidc-auth/node_modules/.pnpm/vite@4.1.4_sass@1.60.0/node_modules/vite/dist/node/chunks/dep-ca21228b.js:39479:29) (x2)
```

**Comment by taikio** [comment]
Try install dependencies and run the project with npm.

PS: i`m using nodejs v16.13.2 and npm v8.1.2

**Comment by Kingside88** [comment]
Maybe the nodeJs Version is the issue. Please consider nodejs 16 is no longer the recommended version instead its 18.

**Comment by taikio** [comment]
I think the problem is unrelated to the Nodejs version.
I made the following test:

1 - I installed Node Js v18.15.0 (npm v9.5.0) through nvm
2 - I deleted the node_modules folder and the package-lock.json file
3 - Installed the project dependencies
4 - I ran the project and tested the navigation

Everything worked normally.

**Comment by Kingside88** [comment]
Ok, I got it. I guess you installed vue and vue-router globally?
Because you miss them both in packages.json. 
So to make it run replace the package.json.
My next goal is to configure it for keycloak. Do you have any experience with keycloak?
```
{
	"private": true,
	"scripts": {
		"build": "nuxt build",
		"dev": "nuxt dev",
		"generate": "nuxt generate",
		"preview": "nuxt preview",
		"postinstall": "nuxt prepare",
		"lint": "eslint ."
	},
	"devDependencies": {
		"@nuxtjs/eslint-config-typescript": "^12.0.0",
		"@pinia/nuxt": "^0.4.6",
		"bootstrap": "^5.2.1",
		"eslint": "^8.32.0",
		"eslint-config-prettier": "^8.6.0",
		"nuxt": "^3.1.0",
		"oidc-client-ts": "^2.2.0",
		"pinia": "2.0.28",
		"prettier": "2.8.3",
		"sass": "^1.54.9",
		"vue": "^3.2.47"
	},
	"dependencies": {
		"@pinia/nuxt": "^0.4.6",
		"bootstrap": "^5.2.1",
		"oidc-client-ts": "^2.2.0",
		"pinia": "2.0.28",
		"sass": "^1.54.9",
		"vue": "^3.2.47",
		"vue-router": "^4.1.6"
	}
}


```

**Comment by taikio** [comment]
I don't think it's a good idea to set a vue version as a dependency. Nuxt is built on top of vue and already handles this dependency internally. This can cause problems in the future if you try to update your Nuxt version.

And answering your question, I have no experience with keycloak.
